version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/workspace

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies- # fallback to using the latest cache if no exact match is found

      - run:
          name: Installing dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Building
          command: npm run build

      - deploy:
          name: Deploying hosting
          command: |
             node_modules/.bin/firebase deploy --token="1/L3_ff-B54wsrKVASA9fNFFB5lWjDDhgpsMp7j4DNiGUDxcDoxQJn-1a-4dQMwSMQ"